default_options = ['---']

main_options = [
    '---',
    '武器',
    '防具',
    '首饰',
    '称号',
    '特殊装备',
    '装扮',
    '宠物',
    '宠物装备',
    '契约效果',
]

minor_options = {
    '装扮': [
        '---',
        '光环',
        '头部装扮',
        '帽子装扮',
        '脸部装扮',
        '胸部装扮',
        '上衣装扮',
        '皮肤装扮',
        '腰部装扮',
        '下装装扮',
        '脚部装扮',
    ],
    '武器': [
        '---',
        '鬼剑士',
        '格斗家',
        '神枪手',
        '魔法师',
        '圣职者',
        '暗夜使者',
        '黑暗武士',
        '缔造者',
    ],
    '防具': ['---', '布甲', '皮甲', '轻甲', '重甲', '板甲'],
    '首饰': [
        '---',
        '手镯',
        '项链',
        '戒指',
    ],
    '特殊装备': [
        '---',
        '辅助装备',
        '魔法石',
    ],
}

patch_options = {
    '鬼剑士': [
        '---',
        '短剑',
        '太刀',
        '巨剑',
        '钝器',
        '光剑',
    ],
    '格斗家': [
        '---',
        '手套',
        '臂铠',
        '爪',
        '拳套',
        '东方棍',
    ],
    '神枪手': [
        '---',
        '自动手枪',
        '手弩',
        '左轮',
        '步枪',
        '手炮',
    ],
    '魔法师': [
        '---',
        '法杖',
        '魔杖',
        '棍棒',
        '矛',
        '扫把',
    ],
    '圣职者': [
        '---',
        '十字架',
        '镰刀',
        '念珠',
        '图腾',
        '战斧',
    ],
    '暗夜使者': [
        '---',
        '手杖',
        '匕首',
        '双剑',
    ],
    '黑暗武士': [
        '---',
        '短剑',
        '太刀',
        '巨剑',
        '钝器',
        '光剑',
    ],
    '缔造者': [
        '---',
        '法杖',
        '魔杖',
        '棍棒',
        '矛',
        '扫把',
    ],
    '布甲': [
        '---',
        '上衣',
        '头肩',
        '下装',
        '腰带',
        '鞋',
    ],
    '皮甲': [
        '---',
        '上衣',
        '头肩',
        '下装',
        '腰带',
        '鞋',
    ],
    '轻甲': [
        '---',
        '上衣',
        '头肩',
        '下装',
        '腰带',
        '鞋',
    ],
    '重甲': [
        '---',
        '上衣',
        '头肩',
        '下装',
        '腰带',
        '鞋',
    ],
    '板甲': [
        '---',
        '上衣',
        '头肩',
        '下装',
        '腰带',
        '鞋',
    ],
}

job_name_mapping = {
    '鬼剑士': '[swordman]',
    '格斗家': '[fighter]',
    '神枪手': '[gunner]',
    '魔法师': '[mage]',
    '圣职者': '[priest]',
    '暗夜使者': '[thief]',
    '黑暗武士': '[demonic swordman]',
    '缔造者': '[creator mage]',
}

equipment_name_mapping = {
    '短剑': 'ssword',
    '太刀': 'katana',
    '巨剑': 'lswd',
    '钝器': 'club',
    '光剑': 'beamswd',
    '手套': 'knuckle',
    '臂铠': 'gauntlet',
    '爪': 'claw',
    '拳套': 'bglove',
    '东方棍': 'tonfa',
    '自动手枪': 'automatic',
    '手弩': 'bowgun',
    '左轮': 'revolver',
    '步枪': 'musket',
    '手炮': 'hcannon',
    '法杖': 'staff',
    '魔杖': 'rod',
    '棍棒': 'pole',
    '矛': 'spear',
    '扫把': 'broom',
    '十字架': 'cross',
    '镰刀': 'scythe',
    '念珠': 'rosary',
    '图腾': 'totem',
    '战斧': 'axe',
    '手杖': 'wand',
    '匕首': 'dagger',
    '双剑': 'twinswd',
    '项链': '[amulet]',
    '手镯': '[wrist]',
    '戒指': '[ring]',
    '辅助装备': '[support]',
    '魔法石': '[magic stone]',
    '称号': 'title',
    '上衣': '[coat]',
    '头肩': '[shoulder]',
    '下装': '[pants]',
    '腰带': '[waist]',
    '鞋': '[shoes]',
    '布甲': 'cl',
    '皮甲': 'lt',
    '轻甲': 'la',
    '重甲': 'ha',
    '板甲': 'mt',
    '光环': '[aurora avatar]',
    '头部装扮': '[hair avatar]',
    '帽子装扮': '[hat avatar]',
    '脸部装扮': '[face avatar]',
    '胸部装扮': '[breast avatar]',
    '上衣装扮': '[coat avatar]',
    '皮肤装扮': '[skin avatar]',
    '腰部装扮': '[waist avatar]',
    '下装装扮': '[pants avatar]',
    '脚部装扮': '[shoes avatar]',
}

rarity_list = [
    '普通',
    '高级',
    '稀有',
    '传承',
    '勇者',
    '神器',
    '领主神器',
    '史诗',
]

item_rarity_list = ['普通', '高级', '稀有', '神器', '史诗', '勇者']

item_category_key_list = [
    '消耗品',
    '材料',
    '副职业',
    '任务道具',
    '附魔宝珠',
    '礼包',
    '时装徽章',
    '契约',
    '宠物道具',
    '变身道具',
    '染色剂',
    '秘药',
    '频道道具',
    '袖珍罐',
    '悬赏令',
    '设计图',
    '地雷',
    '瞬间移动药剂',
    '投掷物',
    '其他',
]

categoryed_stackable_type_dict = {
    '时装徽章': ['[avatar emblem]'],
    '礼包': [
        '[booster random]',
        '[booster selection]',
        '[booster]',
        '[cera booster]',
        '[cera package]',
        '[usable cera package]',
        '[upgrade limit cube]',
    ],
    '契约': ['[contract]'],
    '宠物道具': [
        '[creature expitem]',
        '[creature]',
        '[feed]',
    ],
    '变身道具': ['[disguise random]', '[disguise]'],
    '染色剂': ['[dye]'],
    '附魔宝珠': [
        '[enchant waste]',
    ],
    '秘药': [
        '[expert town potion]',
    ],
    '频道道具': ['[global effect]'],
    '副职业': ['[material expert job]'],
    '材料': ['[material]'],
    '其他': [
        '[etc]',
        '[legacy]',
        '[multi upgradable legacy bonus cera]',
        '[multi upgradable legacy]',
        '[stackable legacy]',
        '[only effect]',
        '[town and dungeon]',
        '[unlimited town and dungeon]',
        '[unlimited etc]',
    ],
    '袖珍罐': ['[upgradable legacy]'],
    '悬赏令': ['[quest receive]'],
    '任务道具': ['[quest]'],
    '设计图': ['[recipe]'],
    '地雷': ['[set]'],
    '瞬间移动药剂': ['[teleport potion]'],
    '投掷物': ['[throw]'],
    '消耗品': ['[waste]', '[unlimited waste]'],
}
